project_name: lwc
archive:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
builds:
  - main: cmd/lwc/main.go
    binary: lwc
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
